Mimir page update and Formatting fixes
thorchain/docs pull request #80
Opened 2024-03-25 23:54 UTC by GrassRootsCrypto

2024-04-24 05:39 UTC, pluto9r commented on frequently-asked-questions/lending.md
> +### What if there's a bank run?
Don't feel comfortable approving this language in official documentation

2024-04-24 05:42 UTC, pluto9r requested changes

2024-04-24 05:42 UTC, pluto9r commented on frequently-asked-questions/lending.md
> +### What if there's a bank run?
Drop this FAQ and I'll approve as-is. This kind of literature belong somewhere else

2024-05-03 05:15 UTC, GrassRootsCrypto commented on frequently-asked-questions/lending.md
> +### What if there's a bank run?
Seen it before… removed

2024-06-04 03:42 UTC, pluto9r approved these changes

2024-06-04 03:43 UTC, merged